"""initial schema

Revision ID: e6e114907ca2
Revises: 
Create Date: 2026-09-21 04:45:26.552752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6e114907ca2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('roll_no', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dept', sa.String(length=255), nullable=True),
    sa.Column('year', sa.String(length=32), nullable=True),
    sa.Column('consent_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll_no')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('event_snapshots',
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('member_refs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('member_id', sa.String(length=32), nullable=False),
    sa.Column('embedding', sa.LargeBinary(length=2048), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('photo_key', sa.String(length=512), nullable=False),
    sa.Column('det_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('thumb_key', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('n_faces', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unknown_clusters',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('rep_face_id', sa.String(length=32), nullable=True),
    sa.Column('resolved_member_id', sa.String(length=32), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['resolved_member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faces',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('photo_id', sa.String(length=32), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('det_score', sa.Float(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(length=2048), nullable=False),
    sa.Column('crop_key', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('matched_member_id', sa.String(length=32), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('candidates', sa.JSON(), nullable=True),
    sa.Column('cluster_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['unknown_clusters.id'], ),
    sa.ForeignKeyConstraint(['matched_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faces')
    op.drop_table('unknown_clusters')
    op.drop_table('photos')
    op.drop_table('member_refs')
    op.drop_table('event_snapshots')
    op.drop_table('users')
    op.drop_table('members')
    op.drop_table('events')
    # ### end Alembic commands ###
